<a href="https://colab.research.google.com/github/LeonardoVS-dev/Fundamentos/blob/main/group_by.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aqui, vou utilizar o arquivo de votação das eleições de 2024 de Roraima para trabalhar com o group_by

In [16]:
import pandas as pd
# Importação do arquivo
#dados_eleitorais = pd.read_csv("/content/votacao_candidato_munzona_2024_RR.csv", encoding="latin-1", sep=";")
#dados_eleitorais = pd.read_csv("/content/votacao_candidato_munzona_2024_RR LIMPADO.csv", encoding="latin-1", sep=";")
dados_eleitorais = pd.read_csv("/content/votacao_candidato_munzona_2024_RR LIMPADO_CORRIGIDO.csv", encoding="latin-1", sep=";")

In [ ]:
# Aqui, crio um dataframe com base nos dados eleitorais importados
dataframe_dados_eleitorais = pd.DataFrame(dados_eleitorais)

# Aqui vai o primeiro group_by: ele serve para agrupar o número do partido
# e o número de votos nominais por cada partido, ou seja,
# traz a soma da contagem de votos por part.
group_numVotos_numPart = dataframe_dados_eleitorais['QT_VOTOS_NOMINAIS'].groupby(dataframe_dados_eleitorais['NR_PARTIDO'])

# No caso, utilizei a função sum() para trazer a soma de todos os votos que
# cada partido recebeu
print(group_numVotos_numPart.sum())

NR_PARTIDO
10     96226
11     83589
12     41526
13      1597
15    166482
18     10783
20     43849
22     14030
23      5380
25       438
27     15395
28      1238
30      5641
40      5242
43      3441
44     57383
45     18851
50      2643
55     29416
65       279
70      2092
77      7887
Name: QT_VOTOS_NOMINAIS, dtype: int64

In [ ]:
# Aqui, crio um dataframe com base nos dados eleitorais importados
dataframe_dados_eleitorais = pd.DataFrame(dados_eleitorais)

# Aqui vai o segundo group_by: ele serve para agrupar o número do partido,
# o nome do partido e o número de votos nominais por cada partido, ou seja,
# traz a soma da contagem de votos por part.
group_numVotos_numPart = dataframe_dados_eleitorais['QT_VOTOS_NOMINAIS'].groupby([dataframe_dados_eleitorais['NR_PARTIDO'], dataframe_dados_eleitorais['NM_PARTIDO']])
print(group_numVotos_numPart.sum())

NR_PARTIDO  NM_PARTIDO
10          REPUBLICANOS                                 96226
11          PROGRESSISTAS                                83589
12          Partido Democrático Trabalhista              41526
13          Partido dos Trabalhadores                     1597
15          Movimento Democrático Brasileiro            166482
18          Rede Sustentabilidade                        10783
20          Podemos                                      43849
22          Partido Liberal                              14030
23          Cidadania                                     5380
25          Partido Renovação Democrática                  438
27          Democracia Cristã                            15395
28          Partido Renovador Trabalhista Brasileiro      1238
30          Partido Novo                                  5641
40          Partido Socialista Brasileiro                 5242
43          Partido Verde                                 3441
44          União Brasil                                 57383
45          Partido da Social Democracia Brasileira      18851
50          Partido Socialismo e Liberdade                2643
55          Partido Social Democrático                   29416
65          Partido Comunista do Brasil                    279
70          AVANTE                                        2092
77          Solidariedade                                 7887
Name: QT_VOTOS_NOMINAIS, dtype: int64

In [ ]:
dataframe_dados_eleitorais = pd.DataFrame(dados_eleitorais)

# Aqui, ele faz a contagem de quantos vereadores (código 13) e
# quantos prefeitos estiveram na disputa
print(dataframe_dados_eleitorais["CD_CARGO"].value_counts())

CD_CARGO
13    1488
11      46
Name: count, dtype: int64

In [ ]:
dataframe_dados_eleitorais = pd.DataFrame(dados_eleitorais)

# Aqui, eu agrupo o número de votos nominais com o código do cargo.
group_numVotos_cdCargo = dataframe_dados_eleitorais['QT_VOTOS_NOMINAIS'].groupby(dataframe_dados_eleitorais['CD_CARGO'])

# Assim, sei qual foi o número médio de votos de cada prefeito e
# de cada vereador através do mean()
print(group_numVotos_cdCargo.mean())

# Já aqui ele retorna o número max de votos que um vereador ou prefeito recebeu
print(group_numVotos_cdCargo.max())

# Aqui é o mínimo
print(group_numVotos_cdCargo.min())

CD_CARGO
11    6714.086957
13     204.677419
Name: QT_VOTOS_NOMINAIS, dtype: float64
CD_CARGO
11    71844
13     2242
Name: QT_VOTOS_NOMINAIS, dtype: int64
CD_CARGO
11    116
13      0
Name: QT_VOTOS_NOMINAIS, dtype: int64

In [20]:
# Group_by com vários índices
dataframe_dados_eleitorais = pd.DataFrame(dados_eleitorais)

#group_multiplo = dataframe_dados_eleitorais.groupby(["NM_MUNICIPIO", "NM_PARTIDO"]).head(30)

dataframe_dados_eleitorais.groupby(["NM_PARTIDO", "CD_CARGO"]).sum()

,NM_PARTIDO,CD_CARGO,NM_MUNICIPIO,NR_ZONA,NM_CANDIDATO,NM_URNA_CANDIDATO,NR_PARTIDO,SG_PARTIDO,QT_VOTOS_NOMINAIS
0,AVANTE,13,BONFIMBONFIMBONFIMBONFIMBONFIMBONFIMBONFIMBONF...,50,ELIAS LIMA DA SILVACHARLES WILSON CALANDRINY M...,ELIAS PICOTECHARLÃOCHICO DO CEMSOLPROFESSOR CH...,700,AVANTEAVANTEAVANTEAVANTEAVANTEAVANTEAVANTEAVAN...,2092
1,Cidadania,11,NORMANDIA,5,NEILA CARVALHO DE OLIVEIRA,NEILA ARAÚJO,23,CIDADANIA,3117
2,Cidadania,13,AMAJARIUIRAMUTÃUIRAMUTÃUIRAMUTÃUIRAMUTÃUIRAMUT...,138,DÉBORA DO NASCIMENTO MACEDOCIZIMAR ADELINO DA ...,MISSIONÁRIA DÉBORACIZIMAR DA ÁGUA FRIAPROF DEL...,644,CIDADANIACIDADANIACIDADANIACIDADANIACIDADANIAC...,2263
3,Democracia Cristã,13,BOA VISTABOA VISTABOA VISTABOA VISTABOA VISTAB...,144,FRANCISCO IDELMOND DE ALBUQUERQUEFRANCISCO IDE...,IDELMOND SPORT E CIAIDELMOND SPORT E CIAJOEL H...,1296,DCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDCDC...,15395
4,Movimento Democrático Brasileiro,11,SÃO JOÃO DA BALIZABOA VISTABOA VISTACARACARAÍ,12,MARCELO JORGE DIAS FERNANDESARTHUR HENRIQUE BR...,MARCELO JORGEARTHUR HENRIQUEARTHUR HENRIQUEANT...,60,MDBMDBMDBMDB,134526
5,Movimento Democrático Brasileiro,13,BOA VISTABOA VISTASÃO JOÃO DA BALIZAMUCAJAÍROR...,522,THIAGO COELHO FOGAÇATHIAGO COELHO FOGAÇAADRIAN...,FOGAÇAFOGAÇAADRIANO COSTAARLENE PRADOCARLINHOS...,1725,MDBMDBMDBMDBMDBMDBMDBMDBMDBMDBMDBMDBMDBMDBMDBM...,31956
6,PROGRESSISTAS,11,ALTO ALEGREIRACEMAPACARAIMASÃO JOÃO DA BALIZAC...,43,JOSE OTACI BARROSO DO NASCIMENTOEDSON DA SILVA...,OTTACIEDINHOWALDERI D AVILALUIZA MAURADIANE CO...,99,PPPPPPPPPPPPPPPPPP,39521
7,PROGRESSISTAS,13,AMAJARIAMAJARIAMAJARIAMAJARIAMAJARIAMAJARISÃO ...,824,MARCELA CAMPOS PINHEIROHUDSON RIBEIRO MOTAELIZ...,MARCELA PINHEIROHUDSON GALVÃOPROFESSORA ELIZÂN...,1914,PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP...,44068
8,Partido Comunista do Brasil,13,BOA VISTABOA VISTABOA VISTABOA VISTA,12,GLEIDSON MARCELO FRANCO FREITASGLEIDSON MARCEL...,GLEIDSON FRANCOGLEIDSON FRANCOTATIANE CASSIANO...,260,PC do BPC do BPC do BPC do B,279
9,Partido Democrático Trabalhista,11,PACARAIMAUIRAMUTÃCAROEBEBONFIM,23,ODILANEI DA SILVA DOS SANTOSABRAÃO OLIVEIRA DA...,DILA SANTOSPROFESSOR ABRAÃOBEBÉ DA FARMÁCIAANT...,48,PDTPDTPDTPDT,7267
10,Partido Democrático Trabalhista,13,IRACEMAIRACEMAIRACEMAIRACEMAIRACEMAIRACEMAIRAC...,785,DINALVA GONSALVES DE OLIVEIRA MELOSANDRA REGIN...,PROFESSORA DINALVA GONSALVESSANDRA REGINATADEU...,1968,PDTPDTPDTPDTPDTPDTPDTPDTPDTPDTPDTPDTPDTPDTPDTP...,34259
11,Partido Liberal,11,CANTÁALTO ALEGRE,8,DANIEL PEDREIRO DA TRINDADEROSA LEOMIR BENEDET...,DANIEL TRINDADEROSA BENEDETTI,44,PLPL,5167
12,Partido Liberal,13,SÃO LUIZSÃO LUIZSÃO LUIZSÃO LUIZSÃO LUIZSÃO LU...,405,ADRIANO DA SILVA FORTINOALCINO MARIANO DA SILV...,ADRIANO DA VANALCINO NETONATANAEL DA 06DANIELP...,2068,PLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPLPL...,8863
13,Partido Novo,11,AMAJARICARACARAÍ,9,PEDRO SARMET MOREIRA DE BARROS SALOMÃOGILDEONE...,DR PEDROGILDEONE ROQUE,60,NOVONOVO,449
14,Partido Novo,13,AMAJARIAMAJARIAMAJARIAMAJARIAMAJARIAMAJARIAMAJ...,197,JAIME ANSOLIN BARDENCATRIANE DUTRA COSTACLEUCI...,JAIME DO ÔNIBUSCATRI DO PROJETO AMAJARICLEUCI ...,1770,NOVONOVONOVONOVONOVONOVONOVONOVONOVONOVONOVONO...,5192
15,Partido Renovador Trabalhista Brasileiro,13,RORAINÓPOLISRORAINÓPOLISRORAINÓPOLISRORAINÓPOL...,104,CLAUDIA DE SOUZA GUEDESABEILTON DE LIMA SILVAA...,CLAUDIA BORGESTINHO DE MARTINS PEREIRATOINHALU...,364,PRTBPRTBPRTBPRTBPRTBPRTBPRTBPRTBPRTBPRTBPRTBPR...,1238
16,Partido Renovação Democrática,13,CANTÁCANTÁCANTÁCANTÁCANTÁCANTÁCANTÁCANTÁ,40,NATÁLIA ALEIXO COELHOJACY MOURA DA TRINDADECLA...,NATÁLIA ALEIXOJACY MOURACLARISSA XAVIERJUVENAL...,200,PRDPRDPRDPRDPRDPRDPRDPRD,438
17,Partido Social Democrático,13,BONFIMBOA VISTABOA VISTAALTO ALEGREPACARAIMAMU...,498,FRANCISCO IVAN DASILVA FILHOTHIAGO DUARTE SARA...,IVAN SILVATHIAGO SARAIVATHIAGO SARAIVAPROFESSO...,6710,PSDPSDPSDPSDPSDPSDPSDPSDPSDPSDPSDPSDPSDPSDPSDP...,29416
18,Partido Socialismo e Liberdade,11,SÃO JOÃO DA BALIZABOA VISTABOA VISTA,10,GUTHEMBERGUER ARISTIDES DA SILVA SOARESLINCOLN...,GUTHEMBERGUER ARISTIDESLINCOLN FREIRELINCOLN F...,150,PSOLPSOLPSOL,1658
19,Partido Socialismo e Liberdade,13,BOA VISTABOA VISTABOA VISTABOA VISTABOA VISTAB...,101,LUCIA ALBERTOLUCIA ALBERTOALZEMIRO TAVARESALZE...,LUCIA PATAMONALUCIA PATAMONAALZEMIRO WAPICHANA...,1050,PSOLPSOLPSOLPSOLPSOLPSOLPSOLPSOLPSOLPSOLPSOLPS...,985
20,Partido Socialista Brasileiro,13,SÃO JOÃO DA BALIZASÃO JOÃO DA BALIZASÃO JOÃO D...,236,CARLOS ALBERTO DOS SANTOSMOISÉS SANTIAGO BORGE...,SANDÚ DO SABIÁMOISÉS SANTIAGOGILSON FILHO DO Z...,1760,PSBPSBPSBPSBPSBPSBPSBPSBPSBPSBPSBPSBPSBPSBPSBP...,5242
21,Partido Verde,11,BOA VISTABOA VISTA,6,MAURO NAKASHIMA DE MELOMAURO NAKASHIMA DE MELO,MAURO NAKASHIMAMAURO NAKASHIMA,86,PVPV,2066
22,Partido Verde,13,UIRAMUTÃCANTÁCANTÁBOA VISTABOA VISTABOA VISTAB...,93,GILBERTO PAULO CORDEIROTALITA PEREIRA VERDEKLE...,GILBERTO DO MORROTALITA PEREIRAKLEITON DO CANT...,989,PVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPVPV,1375
23,Partido da Social Democracia Brasileira,11,BONFIMCANTÁCARACARAÍ,12,KELCIO DO CARMO ARAÚJOROBERTA SERRÃO NOGUEIRAD...,KELCIO BONFIMROBERTA PEIXOTODIEGO FARIAS,135,PSDBPSDBPSDB,9244
24,Partido da Social Democracia Brasileira,13,CARACARAÍCARACARAÍCARACARAÍCARACARAÍCARACARAÍC...,293,ANTONIO DA SILVA LEITAOFRANCILENE DE SOUSAMARI...,ANTÔNIO CHERA DA RRFRAN DA INBELLYBELLYPROFESS...,3150,PSDBPSDBPSDBPSDBPSDBPSDBPSDBPSDBPSDBPSDBPSDBPS...,9607
25,Partido dos Trabalhadores,13,CANTÁCANTÁCANTÁCANTÁCANTÁCANTÁBOA VISTABOA VIS...,94,COSMINO TAVEIRA DOS REISCLEIDIMAR SOUSA SILVAS...,COSMINO DA SÃO RAIMUNDOMILA DO ARAGUAIAPIAUÍ D...,286,PTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPTPT,1597
26,Podemos,11,RORAINÓPOLISAMAJARIPACARAIMASÃO LUIZ,26,PAULA FLORINTINOKLEUDISON MOTA WANDERLEYJOSE H...,PAULA BATISTAKLEUDISON WANDERLEYHERMÓGENES DO ...,80,PODEPODEPODEPODE,15710
27,Podemos,13,ALTO ALEGREALTO ALEGREALTO ALEGREALTO ALEGREAL...,616,AURICELIA MORAES DA SILVAELIAS DUTRA DE FREITA...,PROFESSORA AURICELIAELIAS FREITASMOACY PÉ DE M...,2780,PODEPODEPODEPODEPODEPODEPODEPODEPODEPODEPODEPO...,28139
28,REPUBLICANOS,11,BONFIMMUCAJAÍRORAINÓPOLISCAROEBEALTO ALEGREIRA...,32,ROMUALDO FEITOSA SILVAFRANCISCO RUFINO DE SOUZ...,ROMUALDO FEITOSACHIQUINHO RUFINOPINTO DO EQUAD...,60,REPUBLICANOSREPUBLICANOSREPUBLICANOSREPUBLICAN...,37075
29,REPUBLICANOS,13,BOA VISTABOA VISTARORAINÓPOLISRORAINÓPOLISSÃO ...,823,WALKIRIA RIBEIRO DOS REISWALKIRIA RIBEIRO DOS ...,WALKIRIA RIBEIROWALKIRIA RIBEIROADRIANO SOUZ...,1810,REPUBLICANOSREPUBLICANOSREPUBLICANOSREPUBLICAN...,59151
30,Rede Sustentabilidade,11,BONFIMCANTÁUIRAMUTÃ,17,MARIO NICACIORICARDO DESOUZA SILVABENÍSIO ROBE...,MARIO NICACIORICARDO DO CANAUANIMTUXAUA BENÍSIO,54,REDEREDEREDE,6656
31,Rede Sustentabilidade,13,PACARAIMAPACARAIMAPACARAIMAPACARAIMAPACARAIMAB...,248,ADALTO CIPRIANO COSTADANIEL SAMPAIO ALVESGISEL...,PROFESSOR ADALTODANIEL SAMPAIO COORDENADORA GI...,1044,REDEREDEREDEREDEREDEREDEREDEREDEREDEREDEREDERE...,4127
32,Solidariedade,11,MUCAJAÍ,6,JOELSON SILVA DA COSTA,JOELSON COSTA,77,SOLIDARIEDADE,5982
33,Solidariedade,13,MUCAJAÍMUCAJAÍMUCAJAÍMUCAJAÍMUCAJAÍMUCAJAÍMUCA...,72,ADÃO DOS SANTOS NASCIMENTOFRANCISCO FELICIANO ...,ADÃOZINHODR FELICIANOTOINHA DA AGRICULTURA FAM...,924,SOLIDARIEDADESOLIDARIEDADESOLIDARIEDADESOLIDAR...,1905
34,União Brasil,11,BOA VISTABOA VISTA,6,CATARINA DE LIMA GUERRA DA SILVACATARINA DE LI...,CATARINA GUERRACATARINA GUERRA,88,UNIÃOUNIÃO,40410
35,União Brasil,13,BOA VISTABOA VISTABOA VISTABOA VISTABOA VISTAB...,366,GILIARD MELO MALUFGILIARD MELO MALUFMARLON CRI...,GILIARD GARIMPEIROGILIARD GARIMPEIROMARLON BUS...,3476,UNIÃOUNIÃOUNIÃOUNIÃOUNIÃOUNIÃOUNIÃOUNIÃOUNIÃOU...,16973

In [30]:
dataframe_dados_eleitorais = pd.DataFrame(dados_eleitorais)

# Aqui, o índice do group_by é o nome de cada município. Com a função agg,
# utilizamos o método size() para contar o número total de candidatos nos dois
# cargos em disputa (prefeito e vereador). Além disso, ele traz o número médio
# de votos de cada candidato pelo método mean(). É interessante observar que Boa Vista, a capital
# do estado, é a cidade que mais tem candidatos
dataframe_dados_eleitorais.groupby("NM_MUNICIPIO").agg({"CD_CARGO":"size", "QT_VOTOS_NOMINAIS":"mean"})

                    CD_CARGO  QT_VOTOS_NOMINAIS
NM_MUNICIPIO
ALTO ALEGRE               53         422.339623
AMAJARI                   53         240.471698
BOA VISTA                570         616.992982
BONFIM                    90         224.877778
CANTÁ                    108         264.166667
CARACARAÍ                 88         274.170455
CAROEBE                   43         287.976744
IRACEMA                   47         299.574468
MUCAJAÍ                   93         260.913978
NORMANDIA                 55         294.109091
PACARAIMA                 64         238.250000
RORAINÓPOLIS             118         318.610169
SÃO JOÃO DA BALIZA        52         187.461538
SÃO LUIZ                  39         264.487179
UIRAMUTÃ                  61         227.639344

In [46]:
# Filtragem pelo nome da cidade
dataframe_boavista = dataframe_dados_eleitorais[dataframe_dados_eleitorais["NM_MUNICIPIO"] == "BOA VISTA"]
# Número de candidatos por partido em Boa Vista
dataframe_boavista.groupby("NM_PARTIDO").size()

NM_PARTIDO
Cidadania                                  12
Democracia Cristã                          48
Movimento Democrático Brasileiro           48
PROGRESSISTAS                              48
Partido Comunista do Brasil                 4
Partido Democrático Trabalhista            42
Partido Liberal                            44
Partido Novo                               44
Partido Social Democrático                 46
Partido Socialismo e Liberdade             12
Partido Verde                              18
Partido da Social Democracia Brasileira    22
Partido dos Trabalhadores                  12
Podemos                                    48
REPUBLICANOS                               48
Rede Sustentabilidade                      30
União Brasil                               44
dtype: int64